// Auto-generated by scripts/build-verified.ts
// DO NOT EDIT MANUALLY

export const VERIFIED_EPISODE_COUNT = 13;
export const VERIFIED_QUOTE_COUNT = 151;

export const ZONE_EPISODE_COUNTS = {
  "velocity": 11,
  "perfection": 11,
  "discovery": 11,
  "data": 10,
  "intuition": 9,
  "alignment": 11,
  "chaos": 9,
  "focus": 13
} as const;

export const VERIFIED_EPISODE_SLUGS = [
  "amjad-masad",
  "annie-duke",
  "april-dunford",
  "brian-chesky",
  "casey-winters",
  "dylan-field",
  "elena-verna",
  "jason-fried",
  "marty-cagan",
  "nikita-bier",
  "rahul-vohra",
  "shreyas-doshi",
  "tobi-lutke"
] as const;
