// Auto-generated by scripts/build-verified.ts
// DO NOT EDIT MANUALLY

export const VERIFIED_EPISODE_COUNT = 2;
export const VERIFIED_QUOTE_COUNT = 21;

export const ZONE_EPISODE_COUNTS = {
  "velocity": 2,
  "perfection": 2,
  "discovery": 1,
  "data": 1,
  "intuition": 1,
  "alignment": 2,
  "chaos": 0,
  "focus": 2
} as const;

export const VERIFIED_EPISODE_SLUGS = [
  "brian-chesky",
  "rahul-vohra"
] as const;
