// Auto-generated by scripts/build-verified.ts
// DO NOT EDIT MANUALLY

export const VERIFIED_EPISODE_COUNT = 8;
export const VERIFIED_QUOTE_COUNT = 91;

export const ZONE_EPISODE_COUNTS = {
  "velocity": 8,
  "perfection": 6,
  "discovery": 6,
  "data": 5,
  "intuition": 7,
  "alignment": 6,
  "chaos": 4,
  "focus": 8
} as const;

export const VERIFIED_EPISODE_SLUGS = [
  "amjad-masad",
  "brian-chesky",
  "casey-winters",
  "dylan-field",
  "elena-verna",
  "jason-fried",
  "marty-cagan",
  "rahul-vohra"
] as const;
